// parkersprouse.me
// https://parkersprouse.me/
// Generated by Website Palette Extractor – do not edit by hand.

export const palette = {
  "grey-1": "#52525c",
  "grey-2": "#09090b",
  "ground": "#e4e4e7",
  "ink-1": "#e4e4e7",
  "red": "#d1335b",
  "red-2": "#da5d7c",
} as const;

export type PaletteColor = keyof typeof palette;
